### PR TITLE
Lib i18n must allow to specify application to read resources #10417

### PR DESCRIPTION
**Pull request by anatol-sialitski**

### CODE REVIEW

**Comment by rymsha** [comment]
This is only half-done. getsupportedlocales has the same issue

**Review by rymsha — CHANGES_REQUESTED** [review]
getsupportedlocales has the same issue

**Comment by anatol-sialitski** [comment]
This pr contains fix for getsupportedlocales too

**Review by rymsha — APPROVED** [review]

**Comment by rymsha** [comment]
We decided that it should be vice versa - dependencies between different applications should not be allowed.

**Pull request closed without merging**
