### PR TITLE
Reduce number of issue email notifications

### PR DESCRIPTION
**Pull request by alansemenov**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCommentedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCreatedMailMessageGenerator.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4658963&bid=15601456)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCreatedMailMessageGenerator.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCommentedMailMessageGenerator.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4658963&bid=15601456)

**Comment by GlennRicaud** [comment]
Nice. The behaviour seems correct.

Small problem in the generateRecipients methods like IssueCommentedMailMessageGenerator:generateRecipients.
This will give duplicates in some cases.
Why not instead:
. Create a Set
. Fill the set with the creator and approvers
. Filter out the modifier
. Return the join

Also why the isNew and the special blank check in IssueCreatedMailMessageGenerator:generateRecipients

**Comment by pmi** [comment]
Agree that sets are better option, refactored.

_isNew_ needed for knowing when existing issue has been assigned to new assignees (Case 3 [here ](https://github.com/enonic/xp/issues/7664)) in which case _creator_ is the one who assigned the issue and should not be filtered out.

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCreatedMailMessageGenerator.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4658963&bid=15601456)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCreatedMailMessageGenerator.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4658963&bid=15601456)

**Pull request merged**
