### PR TITLE
XP-2452 Wrong behavior in filter panel: wrong number of contents disp…

### PR DESCRIPTION
**Pull request by Kitamo**
…layed, when content's name typed in search-input

### CODE REVIEW

**Comment by alansemenov** [comment]
Why do we repeat the same code twice in if...else...? This doesn't look right, we should use searchString somehow if it's not empty.
```Typescript
private searchDataAndHandleResponse(contentQuery: ContentQuery, searchString: string) {
            new ContentQueryRequest<ContentSummaryJson,ContentSummary>(contentQuery).
            setExpand(api.rest.Expand.SUMMARY).
            sendAndParse().then((contentQueryResult: ContentQueryResult<ContentSummary,ContentSummaryJson>) => {
                this.getAggregations(contentQuery, contentQueryResult).then((aggregations: api.aggregation.Aggregation[]) => {
                if (api.util.StringHelper.isEmpty(searchString)) {
                    this.updateAggregations(aggregations, true);
                    this.updateHitsCounter(contentQueryResult.getMetadata().getTotalHits());
                    this.toggleAggregationsVisibility(contentQueryResult.getAggregations());
                    new ContentBrowseSearchEvent(contentQueryResult, contentQuery).fire();
                }
                else {
                    this.updateAggregations(aggregations, true);
                    this.updateHitsCounter(contentQueryResult.getMetadata().getTotalHits());
                    this.toggleAggregationsVisibility(contentQueryResult.getAggregations());
                    new ContentBrowseSearchEvent(contentQueryResult, contentQuery).fire();
                }
            });

            }).catch((reason: any) => {
                api.DefaultErrorHandler.handle(reason);
            }).done();
        }
```

**Comment by Kitamo** [comment]
Oops, was refactoring and missed that thing.

**Comment by Kitamo** [comment]
searchString is taken into account when content query request sent, and after current update we won't need to react on it's state in some different way.

**Comment by Kitamo** [comment]
https://github.com/enonic/xp/pull/2685

**Pull request closed without merging**
