### PR TITLE
XP-831 ContentWizardPage: 'Save before close' dialog appears when no …

### PR DESCRIPTION
**Pull request by vbradnitski**
…any data typed and a 'Close' button pressed

### CODE REVIEW

**Comment by vbradnitski** [comment]
1. There is how it worked before - we removed properties in first loop. But that is what I changed. We can't remove properties in forEach loop - it will make a wrong behavior and not all properties will be enumerated. 
2. Agree about moving empty check to Property's method.

**Comment by alansemenov** [comment]
Ok, let's skip #2 then

**Comment by alansemenov** [comment]
By the way, maybe it makes sense to add "removeProperties" method (taking array as an argument) to PropertySet class. I'm sure we remove multiple properties in many places in the code.

**Comment by vbradnitski** [comment]
agree, added.

**Pull request closed without merging**
