### PR TITLE
Application Service - Check application system requirement before sta…

### PR DESCRIPTION
**Pull request by vbradnitski**
…rting #6803

### CODE REVIEW

**Comment by GlennRicaud** [comment]
I like that null or empty will return true. It will avoid problems with applications that do not use the latest gradle plugin.

But I think the following like could cause problems.
``this.systemVersion.getLeft().equals( version )``

Left cannot be null. So I would simply let ``systemVersion.includes( version )`` if systemVersion is not null or empty

**Comment by vbradnitski** [comment]
It based on behavior of VersionRange class. Parsing for exact version string like '5.0' won't throw an error, but will create an object with LEFT=5.0, RIGHT=null. Then there is strange things start:
1. isExact() returns false.
2. includes(version) returns true for any version bigger than LEFT.

I was not sure who controls "X-System-Version" header writing for bundle, maybe user can't access it and it's an extra check. @GlennRicaud ?

**Comment by vbradnitski** [comment]
changed.

**Comment by GlennRicaud** [comment]
Merge in https://github.com/enonic/xp/issues/6938

**Pull request closed without merging**
