### PR TITLE
Errors after inserting a gif file in Live Edit and HtmlArea

### PR DESCRIPTION
**Pull request by alansemenov**

### CODE REVIEW

**Comment by alansemenov** [comment]
@rymsha An animated gif gives NPE when it's being scaled or cropped server-side, so the best option is to serve the original blob and apply scaling client-side.

**Comment by alansemenov** [comment]
But if you know how to implement scaling then please suggest a fix. The gif in question is attached to the original issue.

**Comment by sigdestad** [comment]
Since when did scaling of animated gif's crash? This has been working for a long time afaik, and users only need to specify "use original" if they want to keep the animation.

**Comment by alansemenov** [comment]
Could it be some new(er) format that we don't support, like WebP? It does seem to work on older Gifs, but not on Vegards.

**Comment by rymsha** [comment]
> Since when did scaling of animated gif's crash?

Since people started to create enormously big GIF images with greatest compression tricks :)

> Could it be some new(er) format that we don't support, like WebP?

Well, it is "just" a bug in Java
https://github.com/enonic/xp/issues/8004#issuecomment-609807015

**Comment by rymsha** [comment]
Rising another question: but is there, but turning off GIF scaling due to some special cases, is it worth it?

**Comment by sigdestad** [comment]
I suggest we don't change how stuff works. We already have a solution where user can choose "use original image" to handle such special cases. If this is a Java bug, it will eventually be fixed - or we can start using a better library.

**Comment by alansemenov** [comment]
Well, this is a showstopper for web editors. Not sure if you read the [original issue](https://github.com/enonic/app-contentstudio/issues/1664) from Vegard but he got an endless spinner after uploading his GIF because server crashed trying to serve the image preview (image preview is scaled to 768px by default). User doesn't get a chance to select "Original" because preview crashes rights away after the image is selected.

I guess we could change the preview logic, handle the error, show some placeholder and still allow selecting scaling options even if the preview failed, but this seems strange to me. Another alternative is to set "Original" by default (but this can result in serving a huge image by default). Again, this won't always help because in image component scaling is not up to user at all.

We definitely cannot wait for a fix of the bug that was reported 8 years ago and still hasn't been fixed.

**Comment by sigdestad** [comment]
Proper solution is to handle this error better in the client imho. Then user can choose original and things will work for now. Also just happens for special images right now.

**Comment by alansemenov** [comment]
It's not always up to user. Add an image component to the page -> select Vegard's gif from the selector -> crash. There you cannot choose original.

**Pull request closed without merging**
