### PR TITLE
XP-4733 Don't override native browser outline highlighting

### PR DESCRIPTION
**Pull request by alansemenov**
* Removed overrides of native browser outlining

### CODE REVIEW

**Comment by alansemenov** [comment]
Good point - will fix

**Comment by alansemenov** [comment]
@pmi Fixed - please review

**Comment by alansemenov** [comment]
We don't need outline inside the launcher panel since we already highlight apps when you browse with up and down arrows. It's only the launcher/X icon that we need to outline.

I'm pretty sure I tested the launcher button in apps :) - see attached. Did you run the full build? Strangely enough, _launcher.css is only generated with gradle build, not enough to build with gulp.

image
image

**Comment by pmi** [comment]
Right, full build fixed missing icon ! 
Focus works nicely !

**Pull request merged**
