### PR TITLE
Create async reindex endpoint #7696

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/task/ReindexRunnableTask.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/index/IndexServiceImpl.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4623605&bid=15503054)

**Comment by GlennRicaud** [comment]
Do not include task classes/concepts at this level.
Create a specific listener like it is done for the other operations with progress listener.

**Comment by pmi** [comment]
Introduced ReindexListener and used it instead of generic ProgressReporter

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/task/listener/ReindexListenerImpl.java  3
- modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/task/ReindexRunnableTask.java  1
         

Complexity decreasing per file
==============================
+ modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/index/ReindexExecutor.java  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4623605&bid=15503054)

**Pull request merged**
