### PR TITLE
Distributed Session Management #7529 #7594

### PR DESCRIPTION
**Pull request by rymsha**
- ignite was updated to latest version. To make sure I don't use deprecated API
- worked around ignite bug where it uses wrong classloader for serialisation of ignite internal classes (this is due to conflict between ignite and OSGi which classloader to use)
- removed ignite XP "Cluster" abstraction, because not all nodes will be ignite cluster (if any)
- javax cache updated to version 1.1.1 (now Apache license). Removed rebundle as it is now correct bundle by itself. It is potentially a breaking change, but very unlikely because code is supposed to import 1.x version of javax.cache package. 
- fixed SessionWrapper: it had race conditions for session creation and was storing reference to potentially expired session
- fixed JettyActivator to wait for all dispatchers to be ready. Before it was potential race.
- introduced IgniteSessionStoreFactory (OSGi service) and made IgniteSessionStore OSGi independent. This make multiple dispatchers work again - before they were sharing SessionStore singleton and fail on startup
- worked around Jetty vs Ignite conflict which deserializer to use
- added package import so Auth info deserialization works (OSGi prevents not imported classes to be deserialized).

### CODE REVIEW

**Comment by rymsha** [comment]
I tested it. But it should be fine. We are using R7 in runtime already. But compile with R6.

**Comment by rymsha** [comment]
Consider it dead, but don't close it. I need to make sure I ported all fixes not directly related to Ignite into master

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStore.java  7
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteCacheConfigFactory.java  3
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/reporter/WebSessionReport.java  2
- modules/core/core-ignite/src/test/java/com/enonic/xp/ignite/impl/IgniteClusterTest.java  1
- modules/core/core-ignite/src/test/java/com/enonic/xp/ignite/impl/IgniteAdminClientImplTest.java  1
- modules/core/core-ignite/src/main/java/com/enonic/xp/ignite/impl/IgniteActivator.java  2
- modules/web/web-session/src/test/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStoreTest.java  1
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionData.java  3
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/reporter/WebSessionReporter.java  1
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStoreFactoryActivator.java  3
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStoreFactory.java  1
- modules/core/core-ignite/src/test/java/com/enonic/xp/ignite/impl/IgniteActivatorTest.java  1
- modules/web/web-session/src/test/java/com/enonic/xp/web/session/impl/ignite/reporter/WebSessionReporterTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=4331193&bid=14733097)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/hazelcast/HazelcastSessionDataStoreFactoryActivator.java  3
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/hazelcast/HazelcastInstanceActivator.java  1
- modules/web/web-session/src/test/java/com/enonic/xp/web/session/impl/ignite/reporter/WebSessionReporterTest.java  1
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStore.java  7
- modules/web/web-session/src/test/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStoreTest.java  1
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStoreFactory.java  1
- modules/core/core-ignite/src/main/java/com/enonic/xp/ignite/impl/IgniteActivator.java  2
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteCacheConfigFactory.java  3
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/reporter/WebSessionReport.java  2
- modules/core/core-ignite/src/test/java/com/enonic/xp/ignite/impl/IgniteClusterTest.java  1
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/reporter/WebSessionReporter.java  1
- modules/core/core-ignite/src/test/java/com/enonic/xp/ignite/impl/IgniteAdminClientImplTest.java  1
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionData.java  3
- modules/core/core-ignite/src/test/java/com/enonic/xp/ignite/impl/IgniteActivatorTest.java  1
- modules/web/web-session/src/main/java/com/enonic/xp/web/session/impl/ignite/IgniteSessionDataStoreFactoryActivator.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=4331193&bid=14733097)

**Pull request closed without merging**
