### PR TITLE
XP-75 Image function and image endpoint refactoring and improvements

### PR DESCRIPTION
**Pull request by Kitamo**
-updated according to task description

### CODE REVIEW

**Comment by srs** [comment]
This is scheduled for 6.0.

**Comment by srs** [comment]
Could you update this pull request to be applied on top of 6.0 branch instead of master? Also, make this mergable.

**Comment by Kitamo** [comment]
https://github.com/enonic/xp/pull/1367/files

**Comment by Kitamo** [comment]
https://github.com/enonic/xp/pull/1368

**Pull request closed without merging**
