### PR TITLE
Don't use deep pagination to fetch all entries #7139

### PR DESCRIPTION
**Pull request by vbradnitski**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/index/ReindexExecutor.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5125072&bid=16846530)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/index/ReindexExecutor.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5125072&bid=16846530)

**Comment by rymsha** [comment]
> With this approach dumps must fit into heap. Before we needed to fit only a batch. (surely we could not support more than 500K nodes before this fix, but 500K nodes could consume a lot of heap, but not all nodes have it see #7290 )

Paged approach also stored all ids in collections. with scroll it is just slightly worse.
 
> Also, we probably must revert [00287ab](https://github.com/enonic/xp/commit/00287ab169d2b930fa1b44a6a9c2e7c5fc484834) somehow. For me it is a security concern, actually.

#7951

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/index/ReindexExecutor.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5125072&bid=16846530)

**Pull request closed without merging**
