### PR TITLE
Automatically update the details panel whenever widgets are updated (#4580)

### PR DESCRIPTION
**Pull request by edloidas**
Added widgets update handler when apps are started, stopped or updated.

### CODE REVIEW

**Comment by edloidas** [comment]
I also discovered a problem with details panel. The widgets display is really messed up. To see what I'm talking about, do the following:
* Select a content
* Open Details panel. Info Widget will be displayed.
* Select Dependencies Widget
* Press button to display the Info Widget again
* Select the Version history Widget.

You will see both Dependencies and Version history Widgets. But only one widget should be displayed at a time.

**Comment by alansemenov** [comment]
@edloidas Yes, we already registered a bug on this issue: #4581. I assigned it to you, since you worked with widgets already.

**Comment by edloidas** [comment]
Added 1s latency with debounce function and updated the list of events, that will lead to widgets update. Since widgets don't require the immediate update, 1s is small enough amount of time for the user to wait, until the app is started till it's ready to be used. It's also enough for the server to do some background jobs, and enough time to skip the repeated progress/status app events.

**Comment by alansemenov** [comment]
All the points mentioned above are now fixed and working fine, but I found two more issues:

1. If current widget is uninstalled or deleted, we reset selection to default widget (Version history) but the details panel doesn't seem to re-render correctly (see below):
image

2. When a new widget is deployed or installed, we instantly make it active. This is unnecessary and even irritating, if I currently work with another widget. We should only activate the widget when it's updated.

**Comment by alansemenov** [comment]
About #2 - the behaviour is not exactly what I said, but strange nevertheless - the new widget doesn't seem to be selected, but this code is executed every time I add or remove a widget:
```
if (active) {
  _this.setActiveWidget(active);
  _this.updateActiveWidget();
}
``

If I'm on "Version history" and add or delete a widget, it should not repaint the details panel, since active widget is not affected in any way.

**Comment by edloidas** [comment]
Since the basic solution became too unreadable and had some unsolvable problems, I fully refactored it, almost from scratch:
* All App Events will be handled by the aggregator `handleWidgetsUpdate()`. That function will filter the events and call the debounce function for each Widget. Thus we are now sure to call update for each application, without fear to skip one.
* `handleWidgetUpdate()` call is debounced. It will remove/install/upgrade the widget, that is related to the event.
* The handler won't repaint the active widget if wasn't updated and will switch to default (Info) widget if the active widget was removed.
* __Also__ refactored `getAndInitCustomWidgetViews`: renamed it to `fetchAndInitCustomWidgetViews` and simplified it.

Please, test again for each previous cases, because I may forget to test something.

**Comment by alansemenov** [comment]
Nice job, @edloidas !

**Pull request merged**
