### PR TITLE
Unable to modify media after its created (ai, jpf, pdf, psd and svg) #8281

### PR DESCRIPTION
**Pull request by anatol-sialitski**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-api/src/main/java/com/enonic/xp/inputtype/MediaUploaderType.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MediaFormDataBuilder.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6082402&bid=19912022)

**Comment by sigdestad** [comment]
Hi Tolya, would be nice with a small update on what was wrong?

**Comment by alansemenov** [comment]
@anatol-sialitski The new behaviour should be covered with new tests, I guess?

**Comment by alansemenov** [comment]
> Hi Tolya, would be nice with a small update on what was wrong?

@sigdestad Media content didn't support editing via `modify` API. It never worked, but I guess nobody noticed because usually you don't need to modify media content directly, I guess. Worked for images though, due to special handling, but not for the rest of media types.

**Comment by anatol-sialitski** [comment]
> @anatol-sialitski The new behaviour should be covered with new tests, I guess?

Sure, that PR is marked as draft

**Comment by anatol-sialitski** [comment]
In addition, looks like that `MediaUploderType` used `reference` type instead of `propertySet` by mistake.

**Comment by sigdestad** [comment]
Ah, so that explains it. Will the fix solve everything then?

**Comment by sigdestad** [comment]
Will need release of a 7.4.1 or similar then?

**Comment by alansemenov** [comment]
We'll merge this to 7.3 and 7.4 branches, yes.

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-api/src/main/java/com/enonic/xp/inputtype/MediaUploaderType.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MediaFormDataBuilder.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6082402&bid=19912022)

**Review by rymsha — APPROVED** [review]

**Review by vbradnitski — APPROVED** [review]

**Pull request merged**
