### PR TITLE
Event system improvements

### PR DESCRIPTION
**Pull request by rymsha**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExecutorManager.java  1
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationExecutorServiceImpl.java  2
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationRegistryImpl.java  10
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/event/ScriptEventManagerImpl.java  1
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java  3
         

Complexity decreasing per file
==============================
+ modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/main/MainExecutor.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5578852&bid=18289018)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationExecutorServiceImpl.java  2
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExecutorManager.java  1
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationRegistryImpl.java  10
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/event/ScriptEventManagerImpl.java  1
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java  3
         

Complexity decreasing per file
==============================
+ modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/main/MainExecutor.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5578852&bid=18289018)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationExecutorServiceImpl.java  2
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExecutorManager.java  1
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java  3
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationRegistryImpl.java  10
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/event/ScriptEventManagerImpl.java  1
         

Complexity decreasing per file
==============================
+ modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/main/MainExecutor.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5578852&bid=18289018)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/async/ScriptAsyncServiceImpl.java  2
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java  3
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExecutorManager.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationBundleUtils.java  1
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/event/ScriptEventManagerImpl.java  1
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationRegistryImpl.java  10
         

Complexity decreasing per file
==============================
+ modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/main/MainExecutor.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5578852&bid=18289018)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/event/ScriptEventManagerImpl.java  1
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/async/ScriptAsyncServiceImpl.java  2
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationServiceImpl.java  3
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/executor/ScriptExecutorManager.java  1
- modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationRegistryImpl.java  10
- modules/core/core-api/src/main/java/com/enonic/xp/app/ApplicationBundleUtils.java  1
         

Complexity decreasing per file
==============================
+ modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/main/MainExecutor.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5578852&bid=18289018)

**Comment by rymsha** [comment]
will be done in #8114

**Pull request closed without merging**
