### PR TITLE
XP-2471 Error in console occurs when uploading new image without date…

### PR DESCRIPTION
**Pull request by vbradnitski**
… field set

### CODE REVIEW

**Comment by alansemenov** [comment]
We need to do some refactoring here, a lot of code is duplicated. Please move the following pieces of code into new methods:

1) From onKeyUp handler (two places there) and setSelectedDateTime
```Typescript
this.popup.setSelectedDate(date, true);
this.validUserInput = true;
date ?
  this.popup.setSelectedTime(date.getHours(), date.getMinutes(), true) :
  this.popup.setSelectedTime(null, null, true);
this.selectedDate = date;
```
2) From onSelectedDateChanged and onSelectedTimeChanged handlers:
```Typescript
this.validUserInput = true;
this.input.setValue(this.formatDateTime(this.selectedDate), false, true);
this.notifySelectedDateTimeChanged(new SelectedDateChangedEvent(this.selectedDate));
this.updateInputStyling();
```

Result:
```Typescript
private setDateTime(date: Date) {
  this.popup.setSelectedDate(date, true);
  this.selectedDate = date;
  this.validUserInput = true;
  date ?
    this.popup.setSelectedTime(date.getHours(), date.getMinutes(), true) :
    this.popup.setSelectedTime(null, null, true);
}

public setSelectedDateTime(date: Date) {
            this.input.setValue(this.formatDateTime(date));
            this.setDateTime(date);
        }
...
this.input.onKeyUp((event: KeyboardEvent) => {
var date: Date = null;
                if (api.ui.KeyHelper.isArrowKey(event) || api.ui.KeyHelper.isModifierKey(event)) {
                    return;
                }
                var typedDateTime = this.input.getValue();
                if (api.util.StringHelper.isEmpty(typedDateTime)) {
                    this.setDateTime(null);
                    this.popup.hide();
                } else {
                    date = api.util.DateHelper.parseDateTime(typedDateTime);
                    var dateLength = date && date.getFullYear().toString().length + 12;
                    if (date && date.toString() != "Invalid Date" && typedDateTime.length == dateLength) {
                        this.setDateTime(date);
                        if (!this.popup.isVisible()) {
                            this.popup.show();
                        }
                    } else {
                        this.selectedDate = null;
                        this.validUserInput = false;
                    }
                }
                this.notifySelectedDateTimeChanged(new SelectedDateChangedEvent(date));
                this.updateInputStyling();
            });
...
        
```
```Typescript
private setInputValue(date: Date) {
                this.validUserInput = true;
                this.input.setValue(this.formatDateTime(this.selectedDate), false, true);
                this.notifySelectedDateTimeChanged(new SelectedDateChangedEvent(this.selectedDate));
                this.updateInputStyling();
}
....
            this.popup.onSelectedDateChanged((e: SelectedDateChangedEvent) => {
                if (builder.closeOnSelect) {
                    this.popup.hide();
                }
                this.setDate(e.getDate());
                this.setInputValue();
            });

            this.popup.onSelectedTimeChanged((hours: number, minutes: number) => {
                this.setTime(hours, minutes);
                this.setInputValue();
            });
....
```

**Comment by vbradnitski** [comment]
refactored with a little diff in setDateTime(date: Date) method.

**Comment by alansemenov** [comment]
This looks much better, but is there any reason to repeat 
```this.notifySelectedDateTimeChanged(new SelectedDateChangedEvent(null));```
three times if we always call it anyway? We should move it out of if...else... and call it once before 
```this.updateInputStyling();```(with ```date``` as an argument)

**Comment by vbradnitski** [comment]
no any reason. chnged.

**Pull request merged**
