### PR TITLE
Page Editor/Inspect Panel - Give a warning before changing to page te…

### PR DESCRIPTION
**Pull request by ashklianko**
…mplate #4410

### CODE REVIEW

**Comment by alansemenov** [comment]
Found one small UI issue. If I try to switch from "Custom" to a page template and click "No" in the confirmation, selected option is reverted to "Custom" but when I expand the dropdown it has the page template highlighted (see below). It should originally highlight the currently selected option.

image

**Comment by ashklianko** [comment]
Ok, will fix

**Comment by ashklianko** [comment]
Done.

**Comment by ashklianko** [comment]
That would be non-intuitive; If I read this method I think what is it really doing: selecting option or reverting active selection, that seems totally unrelated to each other

**Pull request merged**
