### PR TITLE
Fix the incorrect progress reporting in content reprocess task #7673

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Comment by GlennRicaud** [comment]
The path taken by the API is a content path, not a node path

**Comment by GlennRicaud** [comment]
Discussed with @pmi.
Closing this PR until next commit

**Comment by pmi** [comment]
Updated PR

**Comment by GlennRicaud** [comment]
You have to check that it is not ContentPath.Root
draft:/ and draft:/content will give you the same content path here I think

**Comment by GlennRicaud** [comment]
It still is incorrect if you send draft:/content
Use params.getSourceBranchPath().getContentPath() instead

**Comment by pmi** [comment]
Right ! Updated !
It doesn't look right that both **/** and **/content** return content named **/content** though ;)

**Pull request merged**
