### PR TITLE
Implement API to fetch layer info for provided contentId #7291

### PR DESCRIPTION
**Pull request by vbradnitski**

### CODE REVIEW

**Comment by sigdestad** [comment]
FYI: Here is a UI that we will implement, and we might also show "child" layer versions of the same item.
Screenshot 2019-08-14 at 16 32 49

So, basically, getting access to all layers where this version exists, and if it is a "local copy" or just inherited would be what we need to begin with. We can then access the content details in separate requests i assume?

**Comment by sigdestad** [comment]
Do you have an example of api signature and response?

**Comment by alansemenov** [comment]
@vbradnitski Pls add content language to response. We also need compare/publish status but I guess that could be fetched in a separate request from the client.

**Comment by GlennRicaud** [comment]
This was discussed and it was supposed to be done in the widget, when rendering server side.
Not as an additional admin API endpoint in the runtime.

I have been told we are short on time and we should merge.
Will merge since it is a prototype, but we should do it differently in the final solution.

**Pull request merged**
