### PR TITLE
XP-475 NewContentDialogue - Add panel that helps user select content …

### PR DESCRIPTION
**Pull request by Kitamo**
…type

-[Added] 'Most Popular block' on top of content types to choose (according to design). New block takes lots of space so set it to be not displayed when height is less than 540px.
-[Updated] Refactored NewContentDialog

### CODE REVIEW

**Comment by Kitamo** [comment]
I like your solution more :)

**Comment by Kitamo** [comment]
Regarding mostPopularBlockMaxItemsAllowedproperty  - I've created it exactly for case when some event will have to reduce(or increase) number of most popular items to show, for example when not enough height (block 2 in your comments). Thus making number of most popular items shown dynamic.

**Comment by alansemenov** [comment]
I see. Well, since we don't need this functionality at the moment, let's remove it for now and add it when/if we need it. For now we'll just keep 2 as a constant.

**Comment by Kitamo** [comment]
Regarding 1) in your comments - not sure it is possible, I've been thinking of putting in initially, but there is <ul> element for content types that allows only <li> inside.

**Comment by Kitamo** [comment]
Done.

**Pull request closed without merging**
