### PR TITLE
Portal Lib - URL generation for content with special characters #7674

### PR DESCRIPTION
**Pull request by vbradnitski**

### CODE REVIEW

**Comment by sigdestad** [comment]
Whoo what is this? Need to know what we are changing before any changes are made. URL handling has IMHO been fine for a long time...

**Comment by vbradnitski** [comment]
We always add normalized contentPath to url during construction. But then we need to remove it for some cases. And normalized contentPath was compared with non-normalized contentPath from portal request. And it fails if there are any characters which have to be normalized.

**Comment by alansemenov** [comment]
> Whoo what is this? Need to know what we are changing before any changes are made. URL handling has IMHO been fine for a long time...

@sigdestad Details are in the [original issue](https://github.com/enonic/xp/issues/7674). And here's the [support case](https://enonic.zendesk.com/agent/tickets/3324).

**Comment by GlennRicaud** [comment]
Perfect :+1:

**Pull request merged**
