### PR TITLE
Implement "Issue List" modal dialog #4652

### PR DESCRIPTION
**Pull request by ashklianko**
-Dialog itself added
-Backend supplies mock data

### CODE REVIEW

**Comment by alansemenov** [comment]
Nice! Just a few small things:
1. Add tooltip to the icon that opens the dialog: "Publishing Issues"
2. Add tooltip to the new Issue icon: "Create an issue"
3. Remove the notepad icon and "Open" button from the list - an issue will be opened on click anywhere. Change cursor on hover to "hand".
4. Change dialog title to "Publishing Issues"
5. Message "No issues found" should be 18px big. It also looks like it's incorrectly centered, too far to the right.
6. The dialog doesn't seem to be correctly centered initially - it does when I slightly resize the window.
7. Seems to be a problem displaying issue Id (#[object Object]) but I guess this will be fixed when the data is in place.
8. Add tooltip to the entire issue div that will display issue's description, but only if it's not empty
9. User name (in "Opened by...") should be bold
10. The focus outline (blue border) is not following active tab:
image

**Comment by ashklianko** [comment]
Fixed everything @alansemenov mentioned except .10

**Comment by ashklianko** [comment]
Regarding backend: still lots to do, test to add etc.

**Comment by alansemenov** [comment]
@runarmyklebust this will be done in #4831

**Pull request merged**
