### PR TITLE
Extra inherit flag in duplicated content #8460

### PR DESCRIPTION
**Pull request by vbradnitski**

### CODE REVIEW

**Review by rymsha — APPROVED** [review]

**Comment by sigdestad** [comment]
What extra flag? I was not aware we needed more?

**Comment by vbradnitski** [comment]
no, it's about `NAME` which shouldn't be in renamed content.

**Comment by sigdestad** [comment]
Not sure if I get it? Is it a change of behaviour or did we add a new inherit flag?

**Comment by rymsha** [comment]
Neither.
Just not very clear issue name.

**Pull request merged**
