### PR TITLE
Enforced code format #7384

### PR DESCRIPTION
**Pull request by rymsha**

### CODE REVIEW

**Comment by alansemenov** [comment]
@GlennRicaud why is this closed? shouldn't we encourage same coding style? plus it's a plus if Codacy will verify commits and warn about unused/illegal imports.

**Comment by GlennRicaud** [comment]
I guess I misunderstood. I thought this was the codestyle that we are already using.
Should we add it in all projects we have?

**Comment by rymsha** [comment]
Keeping things in sync is another story. But code style is something very static. Last time https://github.com/enonic/dev-tools/blob/master/codestyles/idea/Enonic.xml it was updated was Jan 16, 2017
So it should not be that painful. 
But yeah, I would like to change code styles slightly, do to the fact that they are slightly wrong (will be another PR)

**Comment by rymsha** [comment]
Let's try it. It is not hard to revert.

**Pull request merged**
