### PR TITLE
Set correct display name on project roles #7973

### PR DESCRIPTION
**Pull request by vbradnitski**

### CODE REVIEW

**Comment by vbradnitski** [comment]
But `displayName` is a field of `Role` node, we should store expected value there. Do you see a proper way to pass it through api/lib during project create/update actions?

**Comment by vbradnitski** [comment]
And will it have sense if we should roll `displayName` back on project update?

**Comment by sigdestad** [comment]
We need to be able to search for it...

**Comment by rymsha** [comment]
There is another option. 
Don't put the logic of constructing getRoleDisplayName into ProjectRole enum, since ProjectRole should not depend on project name. Move the logic to core-content (keep it in ProjectServiceImple or another class, as you wish)
Move away getRoleKey method from ProjectRole enum as well.

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/project/CreateProjectRootPermissionsCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/project/DeleteProjectRolesCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/project/CreateProjectRolesCommand.java  3
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/project/ProjectPermissions.java  -2
+ modules/core/core-api/src/main/java/com/enonic/xp/project/CreateProjectParams.java  -3
+ modules/core/core-api/src/main/java/com/enonic/xp/project/ModifyProjectParams.java  -3
+ modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectPermissionsJson.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5276160&bid=17278508)

**Pull request closed without merging**
