### PR TITLE
Improve error message when moving a content to a folder with same nam…

### PR DESCRIPTION
**Pull request by pmi**
…e #6059

### CODE REVIEW

**Comment by alansemenov** [comment]
We should not send the literal error message to the client. What we need is to send the task execution status. What we get now is this:

image

What we need in addition is a ``progress.status`` which can be either a int constant (0 - success, 1 - warning, 2 - error) or a string constant ("SUCCESS", "WARNING", "ERROR").

In frontend we will give different error messages based on what kind of operation it was and what status it returned.

**Comment by runarmyklebust** [comment]
Pavel; 
The ProgressReporter-interface is a bit lacking now, so to overcome this issue with not too much work;

1) Refactor according to above complaints into separate result-object etc
2) Implement a toJson in the result, with the following fields (the description created by a separate generator-class)

`{
  "state" : "SUCCESS|WARNING|ERROR",
  "description" : "Your detailed message here"
}`


Serialize this to string into the info-field of the progress-reporter, and this must be handled in the UI to ensure correct color etc @alansemenov

**Comment by alansemenov** [comment]
@pmi We are not going to take this into 6.14 - too many risky changes - so please wait with fixing this and prioritise https://github.com/enonic/xp/pull/6055 and bugs with 6.14.0 milestone

**Comment by pmi** [comment]
@runarmyklebust s'il vous plait ;)

**Pull request merged**
