### PR TITLE
Reduce issue email notifications #7664

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4543093&bid=15288221)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4543093&bid=15288221)

**Comment by alansemenov** [comment]
There's NPE every time the assignee of issue/PR makes changes (adds a comment, closes an issue etc.).

```
15:02:08.640 ERROR c.e.x.a.i.r.r.i.IssueNotificationsSenderImpl - Message sending failed
com.enonic.xp.mail.MailException: null
	at com.enonic.xp.mail.impl.MailServiceImpl.handleException(MailServiceImpl.java:65)
	at com.enonic.xp.mail.impl.MailServiceImpl.send(MailServiceImpl.java:53)
	at com.enonic.xp.admin.impl.rest.resource.issue.IssueNotificationsSenderImpl.lambda$notifyIssueUpdated$3(IssueNotificationsSenderImpl.java:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1082)
	at com.enonic.xp.mail.impl.MailServiceImpl.doSend(MailServiceImpl.java:77)
	at com.enonic.xp.mail.impl.MailServiceImpl.send(MailServiceImpl.java:49)
	... 4 common frames omitted

```

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4543093&bid=15288221)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4543093&bid=15288221)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4543093&bid=15288221)

**Comment by alansemenov** [comment]
It still doesn't work as it should.

Very simple setup: 2 users, user A creates an issue and assigns it to user B. When user B a) adds a comment, or b) closes the issue or c) reopens the issue, then user A should receive an email about this.

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCommentedMailMessageGenerator.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageGenerator.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4543093&bid=15288221)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueCommentedMailMessageGenerator.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueUpdatedMailMessageGenerator.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssueNotificationParamsFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/issue/IssuePublishedMailMessageGenerator.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/enonic/xp/pullRequest?prid=4543093&bid=15288221)

**Comment by GlennRicaud** [comment]
I am a bit confused by the asked changes.

So currently these are the 4 cases of email sent

Issue Created
From: Creator
To: Approver
Copy: -

Issue Updated
From: Modifier
To: Creator
Copy: Approvers

Issue Commented
From: Modifier
To: Creator
Copy: Approvers

Issue Published
From: Publisher
To: Creator
Copy: Approvers


Your asked changes:

1 - "Issue Created" emails are not sent to the creator.
3 - The modifier is never receiving a mail on update.

Let's just discuss quickly what is wanted.

**Pull request closed without merging**
