### PR TITLE
Use ES Search Request Scroll #7139

### PR DESCRIPTION
**Pull request by vbradnitski**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/index/ReindexExecutor.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=5126065&bid=16849130)

**Comment by rymsha** [comment]
Only bug fixes accepted for released versions. This one is improvement. So I close it

**Comment by rymsha** [comment]
I changed my mind. It is a fix for a bug. But let's first fix it in master properly. So, still closed.

**Comment by sigdestad** [comment]
Is this fix related to vacuum? If so, It would be Nice to get it in 7.2.x, as 7.3 seems to be a while away!

**Comment by rymsha** [comment]
Sure @sigdestad https://github.com/enonic/xp/pull/7934

**Pull request closed without merging**
