### PR TITLE
Do not resolve services and assets under site #6918

### PR DESCRIPTION
**Pull request by ashklianko**

### CODE REVIEW

**Comment by ashklianko** [comment]
There's also "site/services" path used in ServiceDescriptorServiceImpl and ServiceDescriptor, is it also to be updated @GlennRicaud ?

**Comment by sigdestad** [comment]
Yes, services must be placed in /resources - should not resolve any of this under /site anymore

**Comment by ashklianko** [comment]
Ok!

**Comment by ashklianko** [comment]
Updated

**Pull request merged**
