### PR TITLE
Cleanup Jackson usage #7472

### PR DESCRIPTION
**Pull request by rymsha**

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/ModelToStringHelper.java  3
         

Complexity decreasing per file
==============================
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/NodeExportResultJson.java  -1
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/ReprocessContentResultJson.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=4735885&bid=15809738)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/ModelToStringHelper.java  3
         

Complexity decreasing per file
==============================
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/SystemLoadResultJson.java  -1
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/NodeExportResultJson.java  -1
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/SystemDumpUpgradeResultJson.java  -2
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/VacuumResultJson.java  -2
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/SystemDumpResultJson.java  -1
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/ReprocessContentResultJson.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=4735885&bid=15809738)

**Comment by GlennRicaud** [comment]
Approved

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/ModelToStringHelper.java  3
         

Complexity decreasing per file
==============================
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/NodeExportResultJson.java  -1
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/SystemDumpResultJson.java  -1
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/SystemDumpUpgradeResultJson.java  -2
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/ReprocessContentResultJson.java  -2
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/VacuumResultJson.java  -2
+ modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/model/SystemLoadResultJson.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=4735885&bid=15809738)

**Pull request merged**
