### PR TITLE
Fetch the list of open issues by content Id #6233

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Comment by jsi** [comment]
What is happening here?  Why has the code coverage been reduced so severely?

**Comment by runarmyklebust** [comment]
I think its not correct @jsi - its the stuff that is not merged yet that differs..

**Comment by jsi** [comment]
Okay.  @runarmyklebust , if you say so.
But, how old is the branch?  Normally, the problem with comparing code coverage percentages, is that the current branch is compared to current master, instead of the latest commit on master that is common to both master and the branch.  Then it may appear as if code coverage has gone down, even if it in fact have stayed the same or even increased.  -  But, it is a long time since we had code coverage below 78,6%, so unless this branch is really old, it is most likely reducing code coverage, although, maybe not -0,06%.

Either way.  Please, just be careful to make sure the code coverage is not reduced when this PR is merged to master!

**Comment by GlennRicaud** [comment]
Changing FindIssuesParams.from/size from int to Integer is the correct solution.
But adapt the construction of FindIssuesParams in IssueResource.countIssues to have a count of 0.

At the same time, use IssuePropertyNames.PUBLISH_REQUEST in the definition IssuePropertyNames.PUBLISH_REQUEST_ITEM_ID

**Comment by pmi** [comment]
Good points, @GlennRicaud ! Updated PR

**Pull request merged**
