### PR TITLE
Event returned by eventlistener in lib-event is not formatted as a ja…

### PR DESCRIPTION
**Pull request by aro**
…vascript object (#5257)

### CODE REVIEW

**Comment by GlennRicaud** [comment]
It works but not a big fan. When using the method rawValue of the interface MapGenerator I am expecting it to be set raw.
Instead in ScriptEventListenerImpl::toJson, we could use
  MapperHelper.serializeMap(entry.getKey(), entry.getValue(), true)

Or actually a better solution that would handle also collections/arrays: Add a new method MapperHelper.serialize taking an Object instead of a map.
  It would check what the object is and call the MapGenerator as it is supposed to be used.

**Comment by aro** [comment]
Fixed so that maps and lists are not converted when using `rawValue` method.

I am not a big fan of having a Helper class in API for something that should just be handled in general. I don't see any reason why maps and lists should not be properly converted when passed to a MapSerializable.
If it's necessary in any case to pass it through without converting, we can use the rawValue method.

**Comment by GlennRicaud** [comment]
Agreed on the value method :). Merged.

**Comment by edwardgronroos** [comment]
Fingers crossed this will reach 6.13 🤞

**Pull request merged**
