### PR TITLE
Replace commons-io with alternatives #7622

### PR DESCRIPTION
**Pull request by rymsha**
had to leave Filesystem Monitor as there is no robust alternative yet.

### CODE REVIEW

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/FileUtils.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4471585&bid=15098346)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/FileUtils.java  4
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/ByteOrderMarkHelper.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4471585&bid=15098346)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/FileUtils.java  4
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/ByteOrderMarkHelper.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4471585&bid=15098346)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/FileUtils.java  4
- modules/server/server-config/src/main/java/com/enonic/xp/server/internal/config/NewConfigWatcher.java  6
- modules/server/server-config/src/main/java/com/enonic/xp/server/internal/config/FilesystemEventPoller.java  5
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/ByteOrderMarkHelper.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4471585&bid=15098346)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/FileUtils.java  4
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/ByteOrderMarkHelper.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4471585&bid=15098346)

**Comment by jsi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/dump/FileUtils.java  4
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/xml/parser/ByteOrderMarkHelper.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/xp/xp/pullRequest?prid=4471585&bid=15098346)

**Comment by rymsha** [comment]
Need commons-io compile in api. til XP version 8

**Pull request closed without merging**
